export const DefaultSeats=[
    {   
        id:"A1",
        seat_status:"unselected"
    },
    {
        id:"A2",
        seat_status:"unselected"
    },
    {
        id:"A3",
        seat_status:"unselected" 
    },
    {
        id:"A4",
        seat_status:"unselected"
    },
    {
        id:"A5",
        seat_status:"unselected"
    },
    {
        id:"A6",
        seat_status:"unselected"
    },

    {
        id:"A7",
        seat_status:"unselected"
    },
    {   
        id:"B1",
        seat_status:"unselected"
    },
    {
        id:"B2",
        seat_status:"unselected"
    },
    {
        id:"B3",
        seat_status:"unselected" 
    },
    {
        id:"B4",
        seat_status:"unselected"
    },
    {
        id:"B5",
        seat_status:"unselected"
    },
    {
        id:"B6",
        seat_status:"unselected"
    },

    {
        id:"B7",
        seat_status:"unselected"
    }
        
    
]